{{- $ui := .Values.s4UICredentials -}}
{{- $api := .Values.s4APICredentials -}}
{{- if or $ui.vaultKey $api.vaultKey }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.s4Credentials.secretName }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: {{ .Values.s4Credentials.secretName }}
    creationPolicy: Owner
  dataFrom:
    {{- if $ui.vaultKey }}
    - extract:
        key: {{ $ui.vaultKey }}
    {{- end }}
    {{- if $api.vaultKey }}
    - extract:
        key: {{ $api.vaultKey }}
    {{- end }}
{{- end }}
