{{- if .Values.s4APICredentials.vaultKey }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s4-api-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: {{ .Values.s4Credentials.secretName }}
    creationPolicy: {{ if .Values.s4UICredentials.vaultKey }}Merge{{ else }}Owner{{ end }}
  dataFrom:
    - extract:
        key: {{ .Values.s4APICredentials.vaultKey }}
{{- end }}
