{{- if .Values.s4Role.buckets }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vp-s4-storage.fullname" . }}-s4-buckets-playbook
  annotations:
    argocd.argoproj.io/sync-wave: "2"
data:
  s4-buckets.yml: |
{{ .Files.Get "playbooks/s4-buckets.yml" | indent 4 }}
  vars/defaults.yml: |
{{ tpl (.Files.Get "playbooks/vars/defaults.yml.tpl") . | indent 4 }}
{{- end }}
